(function(){ "use strict";
var DATA=window.__DATA__||{classmates:[],customFields:[]};
var FIELDS=DATA.customFields||[];
var current=null,li=-1;
function esc(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function attr(s){return esc(s)}
function fv(c,f){if(f.id==="field-relation")return c.relation||"";if(f.id==="field-status")return c.status||"";return c.customValues&&c.customValues[f.id]||""}
function q(){return {search:(document.getElementById("searchInput").value||"").toLowerCase(),rarity:document.getElementById("rarityFilter").value,fields:[]};}
function applyFilters(){var f=q();document.querySelectorAll(".ency-card").forEach(function(card){var c=DATA.classmates.find(function(x){return x.id===card.dataset.id});if(!c){card.style.display="none";return}var ok=true;var hay=[c.name,c.nickname,c.relation,c.status,c.tags,c.bio,c.remark].join(" ").toLowerCase();if(f.search&&!hay.includes(f.search))ok=false;if(f.rarity!=="all"&&c.rarity!==f.rarity)ok=false;FIELDS.forEach(function(field,i){var v=document.getElementById("cfFilter-"+i);if(v&&v.value!=="all"&&fv(c,field)!==v.value)ok=false;});card.style.display=ok?"":"none"});}
function photoURL(p){return p.url||p.dataUrl||""}
function openDetail(id){var c=DATA.classmates.find(function(x){return x.id===id});if(!c)return;current=c;document.getElementById("detailTitle").textContent=c.name||"同学档案";
 var photos=c.photos||[];var imgP=photos.find(function(p){return p.kind!=="video"&&p.cover})||photos.find(function(p){return p.kind!=="video"})||photos[0]||null;var hero=imgP?(imgP.kind==="video"?('<video src="'+attr(photoURL(imgP))+'" controls muted playsinline style="width:100%;height:310px;object-fit:contain;background:#000"></video>'):('<img src="'+attr(photoURL(imgP))+'" alt="'+esc(c.name)+'">')):'<div style="padding:30px;color:#7180a8">暂无照片</div>';
 var gallery=photos.map(function(p,i){if(p.kind==="video")return '<div class="detail-media-tile detail-video-tile" data-detail-photo="'+i+'"><video src="'+attr(photoURL(p))+'" muted preload="metadata"></video><span>▶ 视频</span></div>';return '<div class="detail-media-tile" data-detail-photo="'+i+'"><img src="'+attr(photoURL(p))+'" alt="照片'+(i+1)+'"></div>'}).join("")||'<div style="color:#7180a8;font-size:13px;padding:10px">暂无媒体</div>';
 var fields="";FIELDS.forEach(function(f){var v=fv(c,f);if(v)fields+='<div class="detail-field"><dt>'+esc(f.name)+'</dt><dd>'+esc(v)+'</dd></div>'});
 var tags=(c.tags||"").split(/[,，、]/).map(function(x){return x.trim()}).filter(Boolean).map(function(x){return '<span class="tag">'+esc(x)+'</span>'}).join("");
 document.getElementById("detailContent").innerHTML='<div class="detail-hero"><div><div class="detail-photo">'+hero+'</div><div class="detail-photos">'+gallery+'</div></div><div class="detail-info"><h2>'+esc(c.name||"未命名")+'</h2>'+(c.nickname?'<div class="nick">“'+esc(c.nickname)+'”</div>':'')+'<div class="detail-badges"><span class="detail-badge">'+esc(c.rarity||"")+'</span></div>'+(c.bio?'<p class="detail-bio">'+esc(c.bio)+'</p>':'')+(tags?'<div class="detail-tags">'+tags+'</div>':'')+(fields?'<dl class="detail-fields">'+fields+'</dl>':'')+'</div></div>';
 document.getElementById("detailBackdrop").classList.add("open"); }
function openLightbox(index){if(!current||!current.photos||!current.photos.length)return;li=Math.max(0,Math.min(index,current.photos.length-1));var p=current.photos[li];var img=document.getElementById("lightboxImg"),video=document.getElementById("lightboxVideo");if(p.kind==="video"){img.style.display="none";video.style.display="block";video.src=photoURL(p);video.onloadedmetadata=function(){video.currentTime=p.trimStart||0;video.dataset.trimStart=p.trimStart||0;video.dataset.trimEnd=p.trimEnd||0};video.ontimeupdate=function(){var t=Number(video.dataset.trimEnd||0);if(t>0&&video.currentTime>=t){video.pause();video.currentTime=Number(video.dataset.trimStart||0)}};video.load()}else{video.pause();video.removeAttribute("src");video.style.display="none";img.style.display="block";img.src=photoURL(p)}document.getElementById("lbCaption").textContent="第 "+(li+1)+" / "+current.photos.length+" 个媒体 · "+(p.name||"媒体");document.getElementById("lightbox").classList.add("open")}
function next(d){if(!current||!current.photos.length)return;li=(li+d+current.photos.length)%current.photos.length;openLightbox(li)}
function closeAll(){document.getElementById("detailBackdrop").classList.remove("open");document.getElementById("lightbox").classList.remove("open");var v=document.getElementById("lightboxVideo");if(v){v.pause();v.removeAttribute("src");v.load()}}
document.getElementById("searchInput").addEventListener("input",applyFilters);document.getElementById("rarityFilter").addEventListener("change",applyFilters);
var cfBox=document.getElementById("customFilters");if(cfBox)cfBox.addEventListener("change",applyFilters);
document.getElementById("cardGrid").addEventListener("click",function(e){var card=e.target.closest(".ency-card");if(!card)return;var c=DATA.classmates.find(function(x){return x.id===card.dataset.id});if(!c)return;if(e.target.closest(".avatar-wrap")){var idx=Math.max(0,c.photos.findIndex(function(p){return p.kind!=="video"&&p.cover}));current=c;if(c.photos.length)openLightbox(idx);}else openDetail(card.dataset.id)});
document.getElementById("detailContent").addEventListener("click",function(e){var t=e.target.closest("[data-detail-photo]");if(t)openLightbox(Number(t.dataset.detailPhoto))});
document.getElementById("closeDetailBtn").addEventListener("click",closeAll);document.getElementById("lbClose").addEventListener("click",closeAll);document.getElementById("lbPrev").addEventListener("click",function(){next(-1)});document.getElementById("lbNext").addEventListener("click",function(){next(1)});
document.addEventListener("keydown",function(e){if(e.key==="Escape")closeAll();if(e.key==="ArrowLeft"&&document.getElementById("lightbox").classList.contains("open"))next(-1);if(e.key==="ArrowRight"&&document.getElementById("lightbox").classList.contains("open"))next(1)});
})();
